function getTwoLetterCountryCode(threeLetterCode){
    switch(threeLetterCode){
        case "GER" : return "DE";
        case "USA" : return "US";
        case "MEX" : return "MX";
        case "AUT" : return "AT";
        case "NED" : return "NL";
        case "BEL" : return "BE";
        case "ITA" : return "IT";
        case "MAR" : return "MA";
        case "HUN" : return "HU";
        case "ZIM" : return "ZW";
        case "FRA" : return "FR";
        case "CRO" : return "HR";
        case "SWE" : return "SE";
        case "GRE" : return "GR";
        case "CAN" : return "CA";
        case "AUS" : return "AU";
        case "SUI" : return "CH";
        case "MON" : return "MC";
        case "KOR" : return "KR";
        case "TPE" : return "TW";
        case "SRB" : return "RS";
        case "PHI" : return "PH";
        case "BRA" : return "BR";
        case "PAR" : return "PY";
        case "ECU" : return "EC";
        case "ESP" : return "ES";
        case "JPN" : return "JP";
        case "CZE" : return "CZ";
        case "RUS" : return "RU";
        case "RSA" : return "ZA";
        case "ROU" : return "RO";
        case "SVK" : return "SK";
        case "ISR" : return "IL";
        case "CHI" : return "CL";
        case "VEN" : return "VE";
        case "ARG" : return "AR";
        case "KAZ" : return "KZ";
        case "MAS" : return "MY";
        case "EGY" : return "EG";
        case "PAK" : return "PK";
        case "IND" : return "IN";
        case "PER" : return "PE";
        case "POL" : return "PL";
        case "COL" : return "CO";
        case "KUW" : return "KW";
        case "DOM" : return "DO";
        case "AHO" : return "NL";
        case "FIN" : return "FI";
        case "BUL" : return "BG";
        case "MKD" : return "MK";
        case "DEN" : return "DK";
        case "TUR" : return "TR";
        case "THA" : return "TH";
        case "IRL" : return "IE";
        case "IRI" : return "IR";
        case "LUX" : return "LU";
        case "NOR" : return "NO";
        case "UAE" : return "AE";
        case "MDA" : return "MD";
        case "BIH" : return "BA";
        case "NZL" : return "NZ";
        case "MNE" : return "ME";
        case "GBR" : return "GB";
        case "LAT" : return "LV";
        case "UKR" : return "UA";
        case "SLE" : return "SL";
        case "VIE" : return "VN";
        case "TUN" : return "TN";
        case "HKG" : return "HK";
        case "SLO" : return "SI";
        case "POR" : return "PT";
        case "CYP" : return "CY";
        case "URU" : return "UY";
        case "UZB" : return "UZ";
        case "ALG" : return "DZ";
        case "GEO" : return "GE";
        case "SRI" : return "LK";
        case "BAR" : return "BB";
        case "SOL" : return "SB";
        case "ESA" : return "SV";
        case "BOL" : return "BO";
        case "CHN" : return "CN";
        case "HAI" : return "HT";
        case "BLR" : return "BY";
        case "EST" : return "EE";
        case "INA" : return "ID";
        case "MAD" : return "MG";
        case "SYR" : return "SY";
        case "LIB" : return "LR";
        case "BEN" : return "BJ";
        case "GUA" : return "GT";
        case "PUR" : return "PR";
        case "LTU" : return "LT";
        case "KGZ" : return "KG";
        case "LBA" : return "LY";
        case "QAT" : return "QA";
        case "OMA" : return "OM";
        case "GUM" : return "GU";
        case "SAM" : return "WS";
        case "MHL" : return "MH";
        case "CRC" : return "CR";
        case "SMR" : return "SM";
        case "PAN" : return "PA";
        case "BOT" : return "BW";
        case "SIN" : return "SG";
        case "BDI" : return "BI";
        case "SEN" : return "SN";
        case "BAH" : return "BS";
        case "TOG" : return "TG";
        case "TKM" : return "TM";
        case "GUD" : return "GP";
        case "ANT" : return "AG";
        case "KEN" : return "KE";
        case "ERI" : return "ER";
        case "VAN" : return "VU";
        case "JAM" : return "JM";
    }
}

function getCountryName(threeLetterCode){
    switch(threeLetterCode){
        case "GER" : return "Germany";
        case "USA" : return "United States of America";
        case "MEX" : return "Mexico";
        case "AUT" : return "Austria";
        case "NED" : return "Netherlands";
        case "BEL" : return "Belgium";
        case "ITA" : return "Italy";
        case "MAR" : return "Morocco";
        case "HUN" : return "Hungary";
        case "ZIM" : return "Zimbabwe";
        case "FRA" : return "France";
        case "CRO" : return "Croatia";
        case "SWE" : return "Sweden";
        case "GRE" : return "Greece";
        case "CAN" : return "Canada";
        case "AUS" : return "Australia";
        case "SUI" : return "Switzerland";
        case "MON" : return "Monaco";
        case "KOR" : return "South Korea";
        case "TPE" : return "Taiwan";
        case "SRB" : return "Serbia";
        case "PHI" : return "Philippines";
        case "BRA" : return "Brazil";
        case "PAR" : return "Paraguay";
        case "ECU" : return "Ecuador";
        case "ESP" : return "Spain";
        case "JPN" : return "Japan";
        case "CZE" : return "Czechia";
        case "RUS" : return "Russia";
        case "RSA" : return "South Africa";
        case "ROU" : return "Romania";
        case "SVK" : return "Slovakia";
        case "ISR" : return "Israel";
        case "CHI" : return "Chile";
        case "VEN" : return "Venezuela";
        case "ARG" : return "Argentina";
        case "KAZ" : return "Kazakhstan";
        case "MAS" : return "Malaysia";
        case "EGY" : return "Egypt";
        case "PAK" : return "Pakistan";
        case "IND" : return "India";
        case "PER" : return "Peru";
        case "POL" : return "Poland";
        case "COL" : return "Colombia";
        case "KUW" : return "Kuwait";
        case "DOM" : return "Dominican Rep.";
        case "AHO" : return "Netherlands";
        case "FIN" : return "Finland";
        case "BUL" : return "Bulgaria";
        case "MKD" : return "Macedonia";
        case "DEN" : return "Denmark";
        case "TUR" : return "Turkey";
        case "THA" : return "Thailand";
        case "IRL" : return "Ireland";
        case "IRI" : return "Iran";
        case "LUX" : return "Luxembourg";
        case "NOR" : return "Norway";
        case "UAE" : return "United Arab Emirates";
        case "MDA" : return "Moldova";
        case "BIH" : return "Bosnia and Herz.";
        case "NZL" : return "New Zealand";
        case "MNE" : return "Montenegro";
        case "GBR" : return "United Kingdom";
        case "LAT" : return "Latvia";
        case "UKR" : return "Ukraine";
        case "SLE" : return "Sierra Leone";
        case "VIE" : return "Vietnam";
        case "TUN" : return "Tunisia";
        case "HKG" : return "Hong Kong";
        case "SLO" : return "Slovenia";
        case "POR" : return "Portugal";
        case "CYP" : return "Cyprus";
        case "URU" : return "Uruguay";
        case "UZB" : return "Uzbekistan";
        case "ALG" : return "Algeria";
        case "GEO" : return "Georgia";
        case "SRI" : return "Sri Lanka";
        case "BAR" : return "Barbados";
        case "SOL" : return "Solomon Is.";
        case "ESA" : return "El Salvador";
        case "BOL" : return "Bolivia";
        case "CHN" : return "China";
        case "HAI" : return "Haiti";
        case "BLR" : return "Belarus";
        case "EST" : return "Estonia";
        case "INA" : return "Indonesia";
        case "MAD" : return "Madagascar";
        case "SYR" : return "Syria";
        case "LIB" : return "Liberia";
        case "BEN" : return "Benin";
        case "GUA" : return "Guatemala";
        case "PUR" : return "Puerto Rico";
        case "LTU" : return "Lithuania";
        case "KGZ" : return "Kyrgyzstan";
        case "LBA" : return "Libya";
        case "QAT" : return "Qatar";
        case "OMA" : return "Oman";
        case "GUM" : return "Guam";
        case "SAM" : return "Samoa";
        case "MHL" : return "Marshall Is.";
        case "CRC" : return "Costa Rica";
        case "SMR" : return "San Marino";
        case "PAN" : return "Panama";
        case "BOT" : return "Botswana";
        case "SIN" : return "Singapore";
        case "BDI" : return "Burundi";
        case "SEN" : return "Senegal";
        case "BAH" : return "Bahamas";
        case "TOG" : return "Togo";
        case "TKM" : return "Turkmenistan";
        case "GUD" : return "France";
        case "ANT" : return "Antigua and Barb.";
        case "KEN" : return "Kenya";
        case "ERI" : return "Eritrea";
        case "VAN" : return "Vanuatu";
        case "JAM" : return "Jamaica";
    }
}

function getCountryCodeFromName(name){
    switch(name){
        case "Germany" : return "GER";
        case "United States of America" : return "USA";
        case "Mexico" : return "MEX";
        case "Austria" : return "AUT";
        case "Netherlands" : return "NED";
        case "Belgium" : return "BEL";
        case "Italy" : return "ITA";
        case "Morocco" : return "MAR";
        case "Hungary" : return "HUN";
        case "Zimbabwe" : return "ZIM";
        case "France" : return "FRA";
        case "Croatia" : return "CRO";
        case "Sweden" : return "SWE";
        case "Greece" : return "GRE";
        case "Canada" : return "CAN";
        case "Australia" : return "AUS";
        case "Switzerland" : return "SUI";
        case "Monaco" : return "MON";
        case "South Korea" : return "KOR";
        case "Taiwan" : return "TPE";
        case "Serbia" : return "SRB";
        case "Philippines" : return "PHI";
        case "Brazil" : return "BRA";
        case "Paraguay" : return "PAR";
        case "Ecuador" : return "ECU";
        case "Spain" : return "ESP";
        case "Japan" : return "JPN";
        case "Czechia" : return "CZE";
        case "Russia" : return "RUS";
        case "South Africa" : return "RSA";
        case "Romania" : return "ROU";
        case "Slovakia" : return "SVK";
        case "Israel" : return "ISR";
        case "Chile" : return "CHI";
        case "Venezuela" : return "VEN";
        case "Argentina" : return "ARG";
        case "Kazakhstan" : return "KAZ";
        case "Malaysia" : return "MAS";
        case "Egypt" : return "EGY";
        case "Pakistan" : return "PAK";
        case "India" : return "IND";
        case "Peru" : return "PER";
        case "Poland" : return "POL";
        case "Colombia" : return "COL";
        case "Kuwait" : return "KUW";
        case "Dominican Rep." : return "DOM";
        case "Finland" : return "FIN";
        case "Bulgaria" : return "BUL";
        case "Macedonia" : return "MKD";
        case "Denmark" : return "DEN";
        case "Turkey" : return "TUR";
        case "Thailand" : return "THA";
        case "Ireland" : return "IRL";
        case "Iran" : return "IRI";
        case "Luxembourg" : return "LUX";
        case "Norway" : return "NOR";
        case "United Arab Emirates" : return "UAE";
        case "Moldova" : return "MDA";
        case "Bosnia and Herz." : return "BIH";
        case "New Zealand" : return "NZL";
        case "Montenegro" : return "MNE";
        case "United Kingdom" : return "GBR";
        case "Latvia" : return "LAT";
        case "Ukraine" : return "UKR";
        case "Sierra Leone" : return "SLE";
        case "Vietnam" : return "VIE";
        case "Tunisia" : return "TUN";
        case "Hong Kong" : return "HKG";
        case "Slovenia" : return "SLO";
        case "Portugal" : return "POR";
        case "Cyprus" : return "CYP";
        case "Uruguay" : return "URU";
        case "Uzbekistan" : return "UZB";
        case "Algeria" : return "ALG";
        case "Georgia" : return "GEO";
        case "Sri Lanka" : return "SRI";
        case "Barbados" : return "BAR";
        case "Solomon Is." : return "SOL";
        case "El Salvador" : return "ESA";
        case "Bolivia" : return "BOL";
        case "China" : return "CHN";
        case "Haiti" : return "HAI";
        case "Belarus" : return "BLR";
        case "Estonia" : return "EST";
        case "Indonesia" : return "INA";
        case "Madagascar" : return "MAD";
        case "Syria" : return "SYR";
        case "Liberia" : return "LIB";
        case "Benin" : return "BEN";
        case "Guatemala" : return "GUA";
        case "Puerto Rico" : return "PUR";
        case "Lithuania" : return "LTU";
        case "Kyrgyzstan" : return "KGZ";
        case "Libya" : return "LBA";
        case "Qatar" : return "QAT";
        case "Oman" : return "OMA";
        case "Guam" : return "GUM";
        case "Samoa" : return "SAM";
        case "Marshall Is." : return "MHL";
        case "Costa Rica" : return "CRC";
        case "San Marino" : return "SMR";
        case "Panama" : return "PAN";
        case "Botswana" : return "BOT";
        case "Singapore" : return "SIN";
        case "Burundi" : return "BDI";
        case "Senegal" : return "SEN";
        case "Bahamas" : return "BAH";
        case "Togo" : return "TOG";
        case "Turkmenistan" : return "TKM";
        case "Antigua and Barb." : return "ANT";
        case "Kenya" : return "KEN";
        case "Eritrea" : return "ERI";
        case "Vanuatu" : return "VAN";
        case "Jamaica" : return "JAM";
        default : return undefined;
    }
}